services:
  server:
    # build: server
    image: node:18-alpine
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./server:/app
    command: [ "sh", "-c", "cd /app && npm install && npm start" ]
    depends_on:
      - mongo
    env_file:
      - ./server/.env

  client:
    image: node:18-alpine
    restart: unless-stopped
    ports:
      - 5173:5173
    volumes:
      - ./client:/app
    command: [ "sh", "-c", "cd /app && npm install && npm run dev" ]

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
